# Generated by Django 4.0.1 on 2022-01-23 11:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeRegistered', models.DateTimeField(default=datetime.date.today)),
                ('status', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
