# Generated by Django 4.0.1 on 2022-01-25 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccinationService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermember',
            name='DateTimeRegistered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
