# Generated by Django 4.0.1 on 2022-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccinationService', '0002_alter_registermember_datetimeregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermember',
            name='DateTimeRegistered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
